name: GemRush
version: '${version}'
main: net.teamcastle.gemgrab.GemRush
api-version: '1.21'
commands:
  stats:
    description: View your gemrush stats
  gemrush:
    description: Manage GemRush games