CREATE TABLE IF NOT EXISTS gem_player_stats (
    PlayerID VARCHAR(36) NOT NULL PRIMARY KEY,
    Kills INT NOT NULL DEFAULT 0,
    Deaths INT NOT NULL DEFAULT 0,
    Wins INT NOT NULL DEFAULT 0,
    Losses INT NOT NULL DEFAULT 0,
    GamesPlayed INT NOT NULL DEFAULT 0
)