CREATE TABLE IF NOT EXISTS gem_player_stats (
    PlayerID VARCHAR(36) NOT NULL PRIMARY KEY,
    Kills INT NOT NULL DEFAULT 0,
    Deaths INT NOT NULL DEFAULT 0,
    Wins INT NOT NULL DEFAULT 0,
    Losses INT NOT NULL DEFAULT 0,
    GamesPlayed INT NOT NULL DEFAULT 0
);

INSERT INTO translations (langcode, `key`, `text`, `forserver`) VALUES
    ('de', 'gem.game.full', '§aDas Spiel ist voll! Die Runde startet in §e%seconds% %desc%§a!', 'all'),
    ('en', 'gem.game.full', '§aGame is full! Starting in §e%seconds% %desc%§a!', 'all'),
    ('de', 'gem.game.not-enough', '§cEs sind nicht mehr genug Spieler in der Lobby. Warten auf weitere Spieler...', 'all'),
    ('en', 'gem.game.not-enough', '§cNot enough players to start the game anymore. Countdown cancelled.', 'all'),
    ('de', 'gem.game.victory', '§eSieg!', 'all'),
    ('en', 'gem.game.victory', '§eSweet Victory', 'all'),
    ('de', 'gem.game.defeat', '§8Verloren!', 'all'),
    ('en', 'gem.game.defeat', '§8Defeat!', 'all'),
    ('de', 'gem.game.started', '§aSpiel gestartet', 'all'),
    ('en', 'gem.game.started', '§aGame started', 'all'),
    ('de', 'gem.game.started.luck', '§eViel Glück!', 'all'),
    ('en', 'gem.game.started.luck', '§eGood luck!', 'all'),
    ('de', 'gem.game.draw', '§eDas Spiel endet in einem Unentschieden! Das bedeutet: §8§lSudden Death§e!', 'all'),
    ('en', 'gem.game.draw', '§eThe game ended in a draw!§8§l Sudden death§e starts now!', 'all'),
    ('de', 'gem.', '', 'all'),
    ('en', 'gem.', '', 'all'),
    ('de', 'gem.', '', 'all'),
    ('en', 'gem.', '', 'all'),
    ('de', 'gem.', '', 'all'),
    ('en', 'gem.', '', 'all'),
    ('de', 'gem.', '', 'all'),
    ('en', 'gem.', '', 'all'),
    ('de', 'gem.', '', 'all'),
    ('en', 'gem.', '', 'all'),
    ('de', 'gem.', '', 'all'),
    ('en', 'gem.', '', 'all'),
    ('de', 'gem.', '', 'all'),
    ('en', 'gem.', '', 'all'),
    ('de', 'gem.', '', 'all'),
    ('en', 'gem.', '', 'all'),
    ('de', 'gem.', '', 'all'),
    ('en', 'gem.', '', 'all'),